runtime: nodejs20.11.1

handlers:
- url: /( .* \. (js|css|ico|png|jpg|svg|json|txt|html))$
static_files: build/\1
upload: build/ .* \.(js|css|ico|png|jpg|svg|json|txt|html)

- url: / .*
static_files: build/index.html
unload: build/index.htmll

# Use the latest supported Node. js version